### ISSUE TITLE
Aminator failing on apt_get_update

### ISSUE THREAD

**Issue by jameswomack** [Netflix/aminator#225]
Stack:
```
AptProvisionerUpdateException: apt-get update failed
2015-07-30 16:44:59 - Exception: AptProvisionerUpdateException: apt-get update failed
Traceback (most recent call last):
  File "/apps/python/local/lib/python2.7/site-packages/aminator/core.py", line 69, in aminate
    ok = env.provision()
  File "/apps/python/local/lib/python2.7/site-packages/aminator/environment.py", line 62, in provision
    success = self.provisioner(distro).provision()     # pylint: disable=no-member
  File "/apps/python/local/lib/python2.7/site-packages/aminator/plugins/provisioner/base.py", line 93, in provision
    result = self._provision_package()
  File "/apps/python/local/lib/python2.7/site-packages/aminator/util/metrics.py", line 88, in func_2
    retval = func(obj, *args, **kwargs)
  File "/apps/python/local/lib/python2.7/site-packages/aminator/util/metrics.py", line 75, in func_2
    retval = func(obj, *args, **kwargs)
  File "/apps/python/local/lib/python2.7/site-packages/aminator/util/metrics.py", line 48, in func_2
    retval = func(obj, *args, **kwargs)
  File "/apps/python/local/lib/python2.7/site-packages/aminator/plugins/provisioner/apt.py", line 57, in _provision_package
    result = self._refresh_repo_metadata()
  File "/apps/python/local/lib/python2.7/site-packages/aminator/plugins/provisioner/apt.py", line 51, in _refresh_repo_metadata
    return self.apt_get_update()
  File "/apps/python/local/lib/python2.7/site-packages/aminator/util/metrics.py", line 88, in func_2
    retval = func(obj, *args, **kwargs)
  File "/apps/python/local/lib/python2.7/site-packages/aminator/util/metrics.py", line 75, in func_2
    retval = func(obj, *args, **kwargs)
  File "/apps/python/local/lib/python2.7/site-packages/aminator/util/metrics.py", line 34, in func_2
    retval = func(obj, *args, **kwargs)
  File "<string>", line 2, in apt_get_update
  File "/apps/python/local/lib/python2.7/site-packages/aminator/util/__init__.py", line 64, in _retry
    return f(*args, **kwargs)
  File "/apps/python/local/lib/python2.7/site-packages/aminator/plugins/provisioner/apt.py", line 130, in apt_get_update
    raise AptProvisionerUpdateException('apt-get update failed')
AptProvisionerUpdateException: apt-get update failed
command failed with exit code: 1
no ami generated, assuming failure
```

Bake details:
```
AMI Suffix:	201507292232-trusty-pv
Base OS:	trusty
Base AMI:	trustybase-x86_64-201507240406-ebs
Store Type:	ebs
VM Type:	pv
```

**Comment by bmoyles** [comment]
Handled internally, was a problem with the repo caches, not aminator
